sudo: required
services:
  - docker

before_install:
  - docker build -t racheleyg12/react-test -f ./client/Dockerfile.dev ./client
  
script: 
  - docker run -e CI=true racheleyg12/react-test npm test

after_success:
  - docker build -t racheleyg12/multi-client ./client
  - docker build -t racheleyg12/multi-nginx ./nginx
  - docker build -t racheleyg12/multi-server ./server
  - docker build -t racheleyg12/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push racheleyg12/multi-client
  - docker push racheleyg12/multi-nginx
  - docker push racheleyg12/multi-server
  - docker push racheleyg12/multi-worker
